# https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer
apiVersion: v1
kind: Service
metadata:
  name: paul
spec:
  selector:
    app: paul
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 
  type: LoadBalancer
