maintainers:
  - Spazzy757
# Allows for the /label command
labels: true
# Checks if an issue or an Pull request has a description
empty_description_check:
  enabled: true
  enforced: true
# Settings for branch destroyer
# branch destroyer will not delete your default branch
# set other "protected" branches here
branch_destroyer:
  enabled: true
  protected_branches:
    - main
pull_requests:
  # Allows use of the /assign command
  assign: true
  # Enables DCO check on commits
  dco_check: true
  # Enables Verified Commits check on commits
  verified_commit_check: true
  # Specifies whether to allow for automated merging of Pull Requests
  automated_merge: true
  # Paul will mark a pull request as "stale" if a Pull Request is not updated for this amount of days
  stale_time: 15
  limit_pull_requests:
    max_number: 3
  open_message: |
    Greetings!
    Thank you for contributing to my source code,
    If this is your first time contributing to Paul, please make
    sure to read the [CONTRIBUTING.md](https://github.com/Spazzy757/paul/blob/main/CONTRIBUTING.md)
  cats_enabled: true
  dogs_enabled: true
  allow_approval: true
  giphy_enabled: true
