name: CICD

# events but only for the master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - edited
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0" # The Go version to download (if necessary) and use.


      # Run build of the application
      - name: Run build
        run: go build ./cmd/paul

      # lint    
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      # Run vet
      - name: Run vet
        run: |
          go vet ./...

      # Run testing on the code
      - name: Run testing
        run: go test ./... -v

      - name: Run Coverage
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        if: github.repository == 'Spazzy757/paul'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODCOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
